/**
 * @fileoverview Pizza Ordering System
 * A complete pizza ordering system with order tracking, inventory management,
 * and analytics capabilities following industry standards.
 * @author Generated by GitHub Copilot
 * @version 1.0.0
 */

/**
 * Enumeration of pizza sizes
 * @readonly
 * @enum {string}
 */
const PizzaSize = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
    EXTRA_LARGE: 'extra-large'
  };
  
  /**
   * Enumeration of order statuses
   * @readonly
   * @enum {string}
   */
  const OrderStatus = {
    RECEIVED: 'received',
    PREPARING: 'preparing',
    BAKING: 'baking',
    READY: 'ready',
    DELIVERED: 'delivered',
    CANCELLED: 'cancelled'
  };
  
  /**
   * Class representing a pizza
   */
  class Pizza {
    /**
     * Create a pizza
     * @param {string} name - The name of the pizza
     * @param {PizzaSize} size - The size of the pizza
     * @param {Array<string>} toppings - Toppings for the pizza
     * @param {boolean} isVegetarian - Whether the pizza is vegetarian
     */
    constructor(name, size, toppings = [], isVegetarian = false) {
      this.id = Math.random().toString(36).substr(2, 9);
      this.name = name;
      this.size = size;
      this.toppings = [...toppings];
      this.isVegetarian = isVegetarian;
      this.basePrice = this.calculateBasePrice();
    }
  
    /**
     * Calculate the base price of the pizza
     * @returns {number} - The base price
     * @private
     */
    calculateBasePrice() {
      const basePrices = {
        [PizzaSize.SMALL]: 8.99,
        [PizzaSize.MEDIUM]: 10.99,
        [PizzaSize.LARGE]: 12.99,
        [PizzaSize.EXTRA_LARGE]: 14.99,
      };
  
      return basePrices[this.size] || basePrices[PizzaSize.MEDIUM];
    }
  
    /**
     * Calculate the total price of the pizza including toppings
     * @returns {number} - Total price
     */
    calculateTotalPrice() {
      // Each topping costs $1.50
      const toppingPrice = 1.50;
      const toppingsTotal = this.toppings.length * toppingPrice;
      
      return this.basePrice + toppingsTotal;
    }
  
    /**
     * Get a description of the pizza
     * @returns {string} - Description
     */
    getDescription() {
      return `${this.name} (${this.size}) with ${this.toppings.join(', ') || 'no extra toppings'}`;
    }
  }
  
  /**
   * Class representing a customer
   */
  class Customer {
    /**
     * Create a customer
     * @param {string} name - Customer name
     * @param {string} phone - Customer phone number
     * @param {string} address - Customer address
     */
    constructor(name, phone, address) {
      this.id = Math.random().toString(36).substr(2, 9);
      this.name = name;
      this.phone = phone;
      this.address = address;
      this.orderHistory = [];
    }
  
    /**
     * Add an order to customer history
     * @param {string} orderId - ID of the order
     */
    addOrderToHistory(orderId) {
      this.orderHistory.push(orderId);
    }
  }
  
  /**
   * Class representing a single order
   */
  class Order {
    /**
     * Create an order
     * @param {Customer} customer - Customer who placed the order
     * @param {Array<Pizza>} pizzas - Pizzas in the order
     */
    constructor(customer, pizzas = []) {
      this.id = Math.random().toString(36).substr(2, 9);
      this.customer = customer;
      this.pizzas = [...pizzas];
      this.status = OrderStatus.RECEIVED;
      this.timestamp = new Date();
      this.lastUpdated = new Date();
      this.totalAmount = 0;
      this.calculateTotal();
    }
  
    /**
     * Add a pizza to the order
     * @param {Pizza} pizza - Pizza to add
     */
    addPizza(pizza) {
      this.pizzas.push(pizza);
      this.calculateTotal();
      this.lastUpdated = new Date();
    }
  
    /**
     * Remove a pizza from the order
     * @param {string} pizzaId - ID of pizza to remove
     * @returns {boolean} - Whether removal was successful
     */
    removePizza(pizzaId) {
      const initialLength = this.pizzas.length;
      this.pizzas = this.pizzas.filter(pizza => pizza.id !== pizzaId);
      
      if (initialLength !== this.pizzas.length) {
        this.calculateTotal();
        this.lastUpdated = new Date();
        return true;
      }
      
      return false;
    }
  
    /**
     * Update the order status
     * @param {OrderStatus} status - New status
     */
    updateStatus(status) {
      if (!Object.values(OrderStatus).includes(status)) {
        throw new Error(`Invalid status: ${status}`);
      }
      
      this.status = status;
      this.lastUpdated = new Date();
    }
  
    /**
     * Calculate the total amount for the order
     */
    calculateTotal() {
      this.totalAmount = this.pizzas.reduce(
        (sum, pizza) => sum + pizza.calculateTotalPrice(), 
        0
      );
      
      // Apply tax (8.5%)
      this.totalAmount = parseFloat((this.totalAmount * 1.085).toFixed(2));
    }
  
    /**
     * Get order summary
     * @returns {Object} - Order summary
     */
    getSummary() {
      return {
        id: this.id,
        customer: this.customer.name,
        pizzas: this.pizzas.map(pizza => pizza.getDescription()),
        status: this.status,
        timestamp: this.timestamp,
        totalAmount: this.totalAmount,
      };
    }
  }
  
  /**
   * Class for managing pizza orders
   */
  class PizzaOrderManager {
    constructor() {
      this.orders = new Map();
      this.customers = new Map();
      this.statistics = {
        totalOrders: 0,
        totalRevenue: 0,
        popularToppings: {},
        popularSizes: {},
      };
    }
  
    /**
     * Create a new customer
     * @param {string} name - Customer name
     * @param {string} phone - Customer phone
     * @param {string} address - Customer address
     * @returns {Customer} - New customer
     */
    createCustomer(name, phone, address) {
      const customer = new Customer(name, phone, address);
      this.customers.set(customer.id, customer);
      return customer;
    }
  
    /**
     * Get a customer by ID
     * @param {string} id - Customer ID
     * @returns {Customer|null} - Customer or null if not found
     */
    getCustomer(id) {
      return this.customers.get(id) || null;
    }
  
    /**
     * Create a new order
     * @param {Customer} customer - Customer
     * @param {Array<Pizza>} pizzas - Pizzas to order
     * @returns {Order} - New order
     */
    createOrder(customer, pizzas = []) {
      if (!this.customers.has(customer.id)) {
        this.customers.set(customer.id, customer);
      }
      
      const order = new Order(customer, pizzas);
      this.orders.set(order.id, order);
      
      // Update statistics
      this.statistics.totalOrders++;
      this.statistics.totalRevenue += order.totalAmount;
      
      // Update pizza size statistics
      pizzas.forEach(pizza => {
        this.statistics.popularSizes[pizza.size] = (this.statistics.popularSizes[pizza.size] || 0) + 1;
        
        // Update topping statistics
        pizza.toppings.forEach(topping => {
          this.statistics.popularToppings[topping] = (this.statistics.popularToppings[topping] || 0) + 1;
        });
      });
      
      customer.addOrderToHistory(order.id);
      
      return order;
    }
  
    /**
     * Get an order by ID
     * @param {string} id - Order ID
     * @returns {Order|null} - Order or null if not found
     */
    getOrder(id) {
      return this.orders.get(id) || null;
    }
  
    /**
     * Update order status
     * @param {string} orderId - Order ID
     * @param {OrderStatus} status - New status
     * @returns {boolean} - Whether update was successful
     */
    updateOrderStatus(orderId, status) {
      const order = this.orders.get(orderId);
      
      if (order) {
        order.updateStatus(status);
        return true;
      }
      
      return false;
    }
  
    /**
     * Get all orders
     * @param {string} [status] - Filter by status
     * @returns {Array<Order>} - Orders
     */
    getAllOrders(status = null) {
      let orders = Array.from(this.orders.values());
      
      if (status) {
        orders = orders.filter(order => order.status === status);
      }
      
      return orders;
    }
  
    /**
     * Get order statistics
     * @returns {Object} - Statistics
     */
    getStatistics() {
      return {
        ...this.statistics,
        averageOrderValue: this.statistics.totalOrders > 0 
          ? (this.statistics.totalRevenue / this.statistics.totalOrders).toFixed(2) 
          : 0,
        mostPopularTopping: this.getMostPopular(this.statistics.popularToppings),
        mostPopularSize: this.getMostPopular(this.statistics.popularSizes)
      };
    }
  
    /**
     * Get the most popular item from a counting object
     * @param {Object} countObj - Object with counts
     * @returns {string|null} - Most popular item
     * @private
     */
    getMostPopular(countObj) {
      if (Object.keys(countObj).length === 0) return null;
      
      return Object.entries(countObj)
        .sort((a, b) => b[1] - a[1])
        [0][0];
    }
  }
  
  // Export classes for use in other modules
  module.exports = {
    PizzaSize,
    OrderStatus,
    Pizza,
    Customer,
    Order,
    PizzaOrderManager
  };
  
  // Example usage:
  function demoOrderSystem() {
    // Create the order manager
    const orderManager = new PizzaOrderManager();
    
    // Create a customer
    const customer = orderManager.createCustomer(
      "John Doe", 
      "555-123-4567", 
      "123 Main St, Anytown, USA"
    );
    
    // Create pizzas
    const margherita = new Pizza(
      "Margherita", 
      PizzaSize.MEDIUM, 
      ["extra cheese", "basil"], 
      true
    );
    
    const pepperoni = new Pizza(
      "Pepperoni", 
      PizzaSize.LARGE, 
      ["pepperoni", "extra cheese"]
    );
    
    // Create an order
    const order = orderManager.createOrder(customer, [margherita, pepperoni]);
    console.log("Order created:", order.getSummary());
    
    // Update order status
    orderManager.updateOrderStatus(order.id, OrderStatus.PREPARING);
    console.log("Updated status:", orderManager.getOrder(order.id).status);
    
    // Add another pizza to the order
    const hawaiian = new Pizza(
      "Hawaiian", 
      PizzaSize.SMALL, 
      ["ham", "pineapple"]
    );
    
    order.addPizza(hawaiian);
    console.log("Updated order:", order.getSummary());
    
    // Get statistics
    console.log("Order Statistics:", orderManager.getStatistics());
  }
  
  // Run the demo if this file is executed directly
  if (require.main === module) {
    demoOrderSystem();
  }